### ISSUE TITLE
[voice/video bug] voice is acting strangely, doesn't always establish a connection properly

### ISSUE THREAD

**Issue by Waddle-Doo** [UWPCommunity/Quarrel#395]
Tested and reproduced on Quarrel Insider 20.6.25, including on my fork of the repository.

**Comment by Waddle-Doo** [comment]
As far as I can tell this is fixed as of 20.7.5. Will close, but remind me to reopen this if it starts getting reported again.

**Comment by matthew4850** [comment]
This has not been fixed

**Comment by brunocpmelo** [comment]
Problem still happens to me!!

First 15-30 seconds of communication ok, but then communication is lost.

**Comment by brunocpmelo** [comment]
Problem still happens to me!!

First 15-30 seconds of communication ok, but then communication is lost.

**Comment by Waddle-Doo** [comment]
Please don't spam here, we're aware.

**Comment by sidneisouzajr** [comment]
Hello. Do we have any news about this issue?

**Comment by Waddle-Doo** [comment]
hello there! From my recent testing, optimization appears to have made this less common, but there are still alot of reports that come in about this. it'll be closed if and when a proper fix is implemented.

**Comment by sidneisouzajr** [comment]
Yesterday I tried to use the application twice on XBOX, but unfortunately in less than 5 minutes I lost the audio.
Is there anything I can do, any configuration, to improve?

**Comment by Waddle-Doo** [comment]
try using the latest build of Quarrel Insider

**Comment by sidneisouzajr** [comment]
> try using the latest build of Quarrel Insider

Sorry, but how can I do this on XBOX?
