### ISSUE TITLE
Windows Phone - Crashing

### ISSUE THREAD

**Issue by JanttuFi** [UWPCommunity/Quarrel#95]
Latest version of Quarrel Insider as of now. Latest OS update available for my Lumia 950 XL (1709 ,10.0.15254.590). I can login to the app and see channels and friends, but when I try to do anything, the app crashes. By anything I mean open a text channel in any server or going to the settings. Everything seems to crash the app immediately.

**Comment by matthew4850** [comment]
there is a known crash on mobile with embed/attachments, could you try going to a text channel that you are sure has no embeds/attachments in.

**Comment by JanttuFi** [comment]
Hello. I just tested a channel with just text and it crashes before it even seems to load anything. I made a new empty channel on my server and it opened normally. I sent a message there (just text) and it crashed. I can see on PC that the message was sent. When I try to go back to this channel on my phone, I can't see the text I sent there since it crashes again before it loads. Text I sent was just 'Test'. I've noticed the embed crash on the regular Quarrel version on my phone, but this seems to happen with just loading a channel with simple text. And like I mentioned, I can't even open settings to see if there's something that would help with this issue.

**Comment by matthew4850** [comment]
so it loads the empty channel but crashes when there is a message, I will see if I can find out the problem.

**Comment by JanttuFi** [comment]
Have you managed to track down this issue? Would having Quarrel and Quarrel Insider installed (but not running) at the same time cause this or any other issues?

**Comment by matthew4850** [comment]
This should have been fixed in #97. You should be able to have both installed at the same time.

**Comment by MadafakinRio** [comment]
I still have this problem on mobile, is a new build not pushed there yet?
